### ISSUE TITLE
False positive/negative

### ISSUE THREAD

**Issue by motoko-ayanami** [OSINTI4L/cupidcr4wl#1]
It should be noted that if your ISP, VPN, or proxy provider is blocking certain adult platforms in your region it will cause cupidcr4wl to return false positives. Please ensure this is not the reason you are receiving a false positive/negative prior to submitting an issue.

1. What is the name of the site?
https://www.sweet-passion-escort.de
2. What is the URL of the site?
https://www.sweet-passion-escort.de
3. Is it displaying a false positive or negative?
false positive
4. Additional comments (if any):
User that doesn't exist gets a 301 response code and redirected here : https://www.sweet-passion-escort.de/escort-damen-2/
User that does exist gets a 301 response code and is redirected here : https://www.sweet-passion-escort.de/en/models/charlie/

**Comment by OSINTI4L** [comment]
Updating the [check_text and not_found_text](https://github.com/OSINTI4L/cupidcr4wl/commit/6aadd9fdc0ac98773bc05a148d6261bcdded8a1e) has fixed the issue, thank you for your submission!
